from flask import Flask, render_template, jsonify
from datetime import datetime
import pandas as pd

# Flag for using dummy data generated by simulator program for testing.
USE_SIM_DATA = True

REAL_LOG = "bark_log.csv"
SIM_LOG = "bark_log_dummy.csv"
LOG_FILE = SIM_LOG if USE_SIM_DATA else REAL_LOG

def load_data():
    df = pd.read_csv(LOG_FILE)
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df["hour"] = df["timestamp"].dt.hour
    df["weekday"] = df["timestamp"].dt.dayofweek
    df["date"] = df["timestamp"].dt.date
    return df

df = load_data()
timestamp = datetime.now().strftime("%b %d, %Y at %-I:%M%p")

def format_duration(seconds):
    seconds = int(seconds)

    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60

    duration_str = []
    if hours:
        duration_str.append(f"{hours}h")
    duration_str.append(f"{minutes}m")
    duration_str.append(f"{secs}s")

    return duration_str

app = Flask(__name__)

# Data describing how many barks occur during each hour of the day
@app.route("/data/hourly")
def hourly_data():
    counts = df.groupby("hour").size().reindex(range(24), fill_value=0)

    def format_hour(h):
        ampm = "AM" if h < 12 else "PM"
        h12 = h % 12 or 12
        return f"{h12}{ampm}"
    
    labels = [format_hour(h) for h in range(24)]

    return jsonify({
        "labels": labels,
        "values": counts.tolist()
    })

# Data describing how many barks occur during each day of the week
@app.route("/data/weekday")
def weekday_data():
    counts = df.groupby("weekday").size().reindex(range(7), fill_value=0)
    labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

    return jsonify({
        "labels": labels,
        "values": counts.tolist()
    })

# Data describing how many barks occur each day
@app.route("/data/daily")
def daily_data():
    counts = df.groupby("date").size().sort_index().tail(60)
    return jsonify({
        "labels": counts.index.astype(str).tolist(),
        "values": counts.tolist()
    })

# Data describing how many barks occur each month
@app.route("/data/monthly")
def monthly_data():
    counts = df.groupby(df["timestamp"].dt.to_period('M')).size().sort_index()
    return jsonify({
        "labels": counts.index.astype(str).tolist(),
        "values": counts.tolist()
    })

# Data describing average bark duration per day
@app.route("/data/daily_avg_duration")
def daily_avg_duration_data():
    avg = df.groupby("date")["duration"].mean().sort_index().tail(60)
    return jsonify({
        "labels": avg.index.astype(str).tolist(),
        "values": avg.round(2).tolist()
    })

# Data describing longest barking event per day
@app.route("/data/daily_max_duration")
def daily_max_duration_data():
    max = df.groupby("date")["duration"].max().sort_index().tail(60)
    return jsonify({
        "labels": max.index.astype(str).tolist(),
        "values": max.round(2).tolist()
    })

# Data describing today's barks
@app.route("/data/today")
def today_data():
    today = datetime.now().date()
    today_df = df[df["timestamp"].dt.date == today]

    bark_count = len(today_df)
    total_duration = round(today_df["duration"].sum(), 1)

    return jsonify({
        "count": int(bark_count),
        "duration": format_duration(total_duration)
    })

@app.route("/")
def home():
    df = load_data()
    timestamp = datetime.now().strftime("%b %d, %Y at %-I:%M%p")
    return render_template("index.html", timestamp = timestamp)

app.run(debug=True)
